"""Document formatting, template, citation, and visualisation tools for the Writing Agent."""

import base64
import io
import json
import logging
import os
import re
from datetime import datetime
from typing import Any

from jinja2 import Environment, BaseLoader
from langchain_core.tools import tool

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Report Template
# ---------------------------------------------------------------------------

REPORT_TEMPLATE = """\
# {{ title }}

**Date:** {{ date }}
**Content Type:** {{ content_type }}

---

## Executive Summary

{{ executive_summary }}

---

## Introduction

{{ introduction }}

---

## Methodology

{{ methodology }}

{% if prisma_flow %}
### Study Selection (PRISMA)

{{ prisma_flow }}
{% endif %}

---

## Key Findings

{% for finding in key_findings %}
- {{ finding }}
{% endfor %}

---

{% if intervention_analysis %}
## Intervention Categories

{{ intervention_analysis }}

---
{% endif %}

## Evidence Analysis

{{ evidence_analysis }}

**Evidence Quality:** {{ evidence_quality }}{% if evidence_grade %} | **GRADE:** {{ evidence_grade }}{% endif %}{% if bias_assessment %} | **Risk of Bias:** {{ bias_assessment }}{% endif %}

{% if statistical_summary %}{% set _stat_items = statistical_summary.items() | selectattr('1') | list %}{% if _stat_items %}
**Statistical Summary:**
{% for key, value in _stat_items %}
- **{{ key | title }}:** {{ value }}
{% endfor %}
{% endif %}{% endif %}

{% if chart_path %}

![Forest Plot — Summary of Findings]({{ chart_path }})
*Figure 1. Forest plot summarising pooled effect sizes and 95% confidence intervals.*
{% endif %}

---

## Discussion

{{ discussion }}

---

## Conclusions

{{ conclusions }}

---

## Clinical Recommendations

{{ clinical_recommendations }}

---

## Limitations

{{ limitations }}

---

## References

{% for citation in citations %}
{{ loop.index }}. {{ citation }}
{% endfor %}

---

*Report generated by the Content Intelligence Pipeline*
"""


@tool
def generate_report_from_template(context_json: str) -> str:
    """
    Render a structured clinical/research report using the built-in Jinja2 template.

    Args:
        context_json: JSON string with keys:
            - title (str)
            - content_type (str)
            - executive_summary (str)          — includes clinical recommendations summary
            - introduction (str)
            - methodology (str)
            - prisma_flow (str, optional)      — PRISMA study-selection narrative
            - key_findings (list[str])
            - intervention_analysis (str, optional) — categorised by intervention type
            - evidence_analysis (str)
            - evidence_quality (str)
            - evidence_grade (str, optional)   — GRADE A/B/C/D
            - bias_assessment (str, optional)  — low/moderate/high/unclear
            - statistical_summary (dict, optional)
            - chart_path (str, optional)       — path to a generated chart/forest-plot PNG
            - discussion (str)
            - conclusions (str)
            - clinical_recommendations (str)   — actionable recommendations for clinicians
            - limitations (str)
            - citations (list[str])

    Returns:
        Rendered markdown report string.
    """
    try:
        ctx = json.loads(context_json)
        ctx.setdefault("date", datetime.now().strftime("%B %d, %Y"))
        ctx.setdefault("statistical_summary", {})
        ctx.setdefault("citations", [])
        ctx.setdefault("prisma_flow", "")
        ctx.setdefault("intervention_analysis", "")
        ctx.setdefault("evidence_grade", "")
        ctx.setdefault("bias_assessment", "")
        ctx.setdefault("chart_path", "")
        ctx.setdefault("clinical_recommendations", "")

        env = Environment(loader=BaseLoader())
        tmpl = env.from_string(REPORT_TEMPLATE)
        return tmpl.render(**ctx)

    except (json.JSONDecodeError, TypeError) as exc:
        return f"Template rendering error (bad JSON): {exc}"
    except Exception as exc:
        logger.warning("Report generation failed: %s", exc)
        return f"Report generation error: {exc}"


# ---------------------------------------------------------------------------
# Citation Formatting
# ---------------------------------------------------------------------------


@tool
def format_citation(source_json: str, style: str = "APA") -> str:
    """
    Format a source reference in the requested citation style.

    Args:
        source_json: JSON string with source metadata:
            - authors (list[str])
            - year (str | int)
            - title (str)
            - journal (str, optional)
            - volume (str, optional)
            - issue (str, optional)
            - pages (str, optional)
            - url (str, optional)
            - doi (str, optional)
        style: Citation style — 'APA', 'MLA', or 'Vancouver' (default 'APA').

    Returns:
        Formatted citation string.
    """
    try:
        src = json.loads(source_json)
    except (json.JSONDecodeError, TypeError) as exc:
        return f"Invalid source JSON: {exc}"

    authors = src.get("authors", ["Unknown Author"])
    year = src.get("year", "n.d.")
    title = src.get("title", "Untitled")
    journal = src.get("journal", "")
    volume = src.get("volume", "")
    issue = src.get("issue", "")
    pages = src.get("pages", "")
    url = src.get("url", "")
    doi = src.get("doi", "")

    style = style.upper()

    if style == "APA":
        author_str = _apa_authors(authors)
        citation = f"{author_str} ({year}). {title}."
        if journal:
            citation += f" *{journal}*"
            if volume:
                citation += f", *{volume}*"
                if issue:
                    citation += f"({issue})"
            if pages:
                citation += f", {pages}"
            citation += "."
        if doi:
            citation += f" https://doi.org/{doi}"
        elif url:
            citation += f" Retrieved from {url}"
        return citation

    elif style == "MLA":
        author_str = _mla_authors(authors)
        citation = f'{author_str} "{title}."'
        if journal:
            citation += f" *{journal}*"
            if volume:
                citation += f", vol. {volume}"
            if issue:
                citation += f", no. {issue}"
        citation += f", {year}"
        if pages:
            citation += f", pp. {pages}"
        citation += "."
        if url:
            citation += f" {url}."
        return citation

    elif style == "VANCOUVER":
        author_str = ", ".join(a.split(",")[0] if "," in a else a.split()[-1] for a in authors[:6])
        citation = f"{author_str}. {title}."
        if journal:
            citation += f" {journal}. {year}"
            if volume:
                citation += f";{volume}"
            if issue:
                citation += f"({issue})"
            if pages:
                citation += f":{pages}"
            citation += "."
        if doi:
            citation += f" doi:{doi}"
        return citation

    else:
        return f"Unsupported citation style '{style}'. Use APA, MLA, or Vancouver."


def _apa_authors(authors: list[str]) -> str:
    if not authors:
        return "Unknown Author"
    if len(authors) == 1:
        return authors[0]
    if len(authors) <= 7:
        return ", ".join(authors[:-1]) + ", & " + authors[-1]
    return ", ".join(authors[:6]) + ", ... " + authors[-1]


def _mla_authors(authors: list[str]) -> str:
    if not authors:
        return "Unknown Author."
    if len(authors) == 1:
        return authors[0] + "."
    return authors[0] + ", et al."


# ---------------------------------------------------------------------------
# Section Extraction Helper
# ---------------------------------------------------------------------------


@tool
def extract_markdown_section(markdown_text: str, section_title: str) -> str:
    """
    Extract a specific section from a markdown document by its heading.

    Args:
        markdown_text: Full markdown document text.
        section_title: The heading title to extract (case-insensitive).

    Returns:
        The content of the section, or an empty string if not found.
    """
    pattern = rf"(?:^|\n)#{{1,3}}\s+{re.escape(section_title)}\s*\n(.*?)(?=\n#{{1,3}}\s|\Z)"
    match = re.search(pattern, markdown_text, re.IGNORECASE | re.DOTALL)
    return match.group(1).strip() if match else ""


# ---------------------------------------------------------------------------
# Chart and Forest Plot Visualisations
# ---------------------------------------------------------------------------


@tool
def create_bar_chart(data_json: str, title: str = "Chart", output_path: str = "chart.png") -> str:
    """
    Create a bar chart from labelled data and return it as a base64 data URI.

    Args:
        data_json: JSON string with 'labels' and 'values' lists.
                   Example: '{"labels": ["A", "B"], "values": [10, 20]}'
        title: Chart title.
        output_path: Unused (kept for API compatibility).

    Returns:
        A base64-encoded data URI string (data:image/png;base64,...) that can be
        embedded directly into markdown as ![chart](<returned_value>).
    """
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        data: dict[str, Any] = json.loads(data_json)
        labels = data.get("labels", [])
        values = data.get("values", [])

        if not labels or not values or len(labels) != len(values):
            return "Error: 'labels' and 'values' must be non-empty lists of equal length."

        fig, ax = plt.subplots(figsize=(10, 6))
        bars = ax.bar(labels, values, color="steelblue", edgecolor="white")
        ax.set_title(title, fontsize=14, fontweight="bold")
        ax.set_ylabel("Value")
        ax.bar_label(bars, fmt="%.2f", padding=3)
        plt.tight_layout()

        buf = io.BytesIO()
        plt.savefig(buf, format="png", dpi=150)
        plt.close()
        buf.seek(0)
        b64 = base64.b64encode(buf.read()).decode("utf-8")
        return f"data:image/png;base64,{b64}"

    except (json.JSONDecodeError, KeyError) as exc:
        return f"Data format error: {exc}"
    except Exception as exc:
        logger.warning("Chart creation failed: %s", exc)
        return f"Chart error: {exc}"


@tool
def create_forest_plot(
    studies_json: str,
    outcome_label: str = "Effect Size (95% CI)",
    output_path: str = "forest_plot.png",
) -> str:
    """
    Create a forest plot visualising effect sizes and confidence intervals, and return it
    as a base64 data URI ready for embedding in markdown.

    Use this to present meta-analytic or multi-study evidence visually, following
    standard medical reporting conventions. Ideal for statistical_summary data where
    each outcome has a mean effect and 95% CI.

    Args:
        studies_json: JSON string — a list of objects, each with:
            - label (str): outcome name or study name (e.g. "HbA1c reduction")
            - effect_size (float): point estimate (mean difference, OR, RR, etc.)
            - ci_lower (float): lower bound of 95% confidence interval
            - ci_upper (float): upper bound of 95% confidence interval
            Example: '[{"label":"HbA1c reduction","effect_size":-0.5,"ci_lower":-0.7,"ci_upper":-0.3}]'

        outcome_label: X-axis label describing the outcome metric.
        output_path: Unused (kept for API compatibility).

    Returns:
        A base64-encoded data URI string (data:image/png;base64,...) — use this value
        directly as the chart_path in generate_report_from_template context JSON.
    """
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        studies: list[dict[str, Any]] = json.loads(studies_json)
        if not studies:
            return "Error: No studies provided for forest plot."

        labels = [s.get("label", f"Study {i+1}") for i, s in enumerate(studies)]
        effects = [float(s["effect_size"]) for s in studies]
        ci_lowers = [float(s["ci_lower"]) for s in studies]
        ci_uppers = [float(s["ci_upper"]) for s in studies]

        n = len(studies)
        fig, ax = plt.subplots(figsize=(11, max(4, n * 0.8 + 2.5)))

        y_positions = list(range(n - 1, -1, -1))  # top-to-bottom

        colors = ["#2563eb", "#16a34a", "#dc2626", "#9333ea", "#ea580c", "#0891b2"]
        for i, (y, eff, lo, hi) in enumerate(zip(y_positions, effects, ci_lowers, ci_uppers)):
            color = colors[i % len(colors)]
            # CI bar
            ax.plot([lo, hi], [y, y], color=color, linewidth=2.5, alpha=0.7, solid_capstyle="round")
            # Whisker caps
            ax.plot([lo, lo], [y - 0.15, y + 0.15], color=color, linewidth=2)
            ax.plot([hi, hi], [y - 0.15, y + 0.15], color=color, linewidth=2)
            # Effect square
            ax.plot(eff, y, "D", color=color, markersize=9, zorder=5)
            # Annotate effect value
            ax.annotate(
                f"{eff:+.2f} [{lo:+.2f}, {hi:+.2f}]",
                xy=(hi, y),
                xytext=(6, 0),
                textcoords="offset points",
                fontsize=8.5,
                va="center",
                color="#374151",
            )

        # Reference line at 0
        ax.axvline(0, color="#6b7280", linestyle="--", linewidth=1.2, alpha=0.8)

        ax.set_yticks(y_positions)
        ax.set_yticklabels(labels, fontsize=10)
        ax.set_xlabel(outcome_label, fontsize=11)
        ax.set_title("Summary of Findings — Forest Plot", fontsize=13, fontweight="bold", pad=12)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.grid(axis="x", alpha=0.3, linestyle=":")

        # Extend x-axis right to leave room for annotations
        xmin, xmax = ax.get_xlim()
        ax.set_xlim(xmin, xmax + (xmax - xmin) * 0.35)

        plt.tight_layout()

        buf = io.BytesIO()
        plt.savefig(buf, format="png", dpi=150, bbox_inches="tight")
        plt.close()
        buf.seek(0)
        b64 = base64.b64encode(buf.read()).decode("utf-8")
        return f"data:image/png;base64,{b64}"

    except (json.JSONDecodeError, KeyError, ValueError) as exc:
        return f"Data format error: {exc}"
    except Exception as exc:
        logger.warning("Forest plot creation failed: %s", exc)
        return f"Forest plot error: {exc}"


# ---------------------------------------------------------------------------
# Dynamic Plotly Visualisation
# ---------------------------------------------------------------------------


@tool
def create_plotly_chart(chart_spec_json: str) -> str:
    """
    Dynamically generate a Plotly chart from a flexible chart specification.

    Supports multiple chart types and multi-series data. Returns the Plotly figure
    as JSON (always) and a PNG base64 data URI (if the kaleido package is installed).

    Args:
        chart_spec_json: JSON string with:
            - chart_type (str): One of "bar" | "line" | "scatter" | "pie" |
              "heatmap" | "box" | "area" | "waterfall". Default "bar".
            - title (str): Chart title.
            - x_label (str, optional): X-axis label.
            - y_label (str, optional): Y-axis label.
            - data (list[dict]): One dict per series/trace. Supported keys per
              series vary by chart_type:
                • bar / line / scatter / area:
                    x (list), y (list), name (str),
                    error_y (dict, optional) — e.g. {"array": [0.1, 0.2]}
                • pie:
                    labels (list), values (list), name (str),
                    hole (float 0-1, optional) — 0 = pie, >0 = donut
                • heatmap:
                    x (list), y (list), z (list[list]),
                    colorscale (str, optional, default "Blues")
                • box:
                    y (list), name (str),
                    boxpoints (str, optional) — "outliers" | "all" | False
                • waterfall:
                    x (list), y (list), name (str),
                    measure (list, optional) — "relative" | "total" | "absolute"
            - layout (dict, optional): Any Plotly layout overrides
              (e.g. {"barmode": "group", "showlegend": true}).
            - orientation (str, optional): "v" (default) or "h" for bar charts.

        Example — grouped bar chart:
            {
              "chart_type": "bar",
              "title": "HbA1c Reduction by Intervention",
              "x_label": "Intervention",
              "y_label": "HbA1c Change (%)",
              "data": [
                {"x": ["Diet", "Exercise", "Combined"], "y": [-0.5, -0.7, -1.2],
                 "name": "6-month", "error_y": {"array": [0.1, 0.15, 0.2]}},
                {"x": ["Diet", "Exercise", "Combined"], "y": [-0.8, -1.0, -1.5],
                 "name": "12-month"}
              ],
              "layout": {"barmode": "group"}
            }

    Returns:
        JSON string with:
            - "plotly_json" (str): Full Plotly figure JSON for interactive embedding.
            - "png_base64" (str, optional): data:image/png;base64,... URI for
              static markdown embedding (only present when kaleido is installed).
        On error returns a plain error string.
    """
    try:
        import plotly.graph_objects as go
        import plotly.io as pio
    except ImportError:
        return "Plotly is not installed. Run: pip install plotly"

    try:
        spec: dict[str, Any] = json.loads(chart_spec_json)
        chart_type = spec.get("chart_type", "bar").lower()
        title = spec.get("title", "Chart")
        x_label = spec.get("x_label", "")
        y_label = spec.get("y_label", "")
        series_list: list[dict] = spec.get("data", [])
        layout_overrides: dict = spec.get("layout", {})
        orientation = spec.get("orientation", "v")

        _SUPPORTED = {"bar", "line", "scatter", "pie", "heatmap", "box", "area", "waterfall"}
        if chart_type not in _SUPPORTED:
            return (
                f"Unsupported chart_type '{chart_type}'. "
                f"Supported types: {', '.join(sorted(_SUPPORTED))}."
            )

        traces: list[go.BaseTraceType] = []

        for series in series_list:
            name = series.get("name", "")
            x = series.get("x", [])
            y = series.get("y", [])
            error_y = series.get("error_y")

            if chart_type == "bar":
                traces.append(go.Bar(
                    x=x, y=y, name=name,
                    orientation=orientation,
                    error_y=error_y,
                ))

            elif chart_type == "line":
                traces.append(go.Scatter(
                    x=x, y=y, name=name,
                    mode="lines+markers",
                    error_y=error_y,
                ))

            elif chart_type == "area":
                traces.append(go.Scatter(
                    x=x, y=y, name=name,
                    mode="lines",
                    fill="tozeroy",
                    error_y=error_y,
                ))

            elif chart_type == "scatter":
                traces.append(go.Scatter(
                    x=x, y=y, name=name,
                    mode="markers",
                    marker=series.get("marker", {}),
                    error_y=error_y,
                ))

            elif chart_type == "pie":
                traces.append(go.Pie(
                    labels=series.get("labels", x),
                    values=series.get("values", y),
                    name=name,
                    hole=series.get("hole", 0),
                ))

            elif chart_type == "heatmap":
                traces.append(go.Heatmap(
                    x=x,
                    y=y,
                    z=series.get("z", []),
                    colorscale=series.get("colorscale", "Blues"),
                ))

            elif chart_type == "box":
                traces.append(go.Box(
                    y=y, name=name,
                    boxpoints=series.get("boxpoints", "outliers"),
                ))

            elif chart_type == "waterfall":
                traces.append(go.Waterfall(
                    x=x, y=y, name=name,
                    measure=series.get("measure", ["relative"] * len(y)),
                ))

        layout = go.Layout(
            title={"text": title, "x": 0.5, "xanchor": "center"},
            xaxis={"title": x_label},
            yaxis={"title": y_label},
            template="plotly_white",
            **layout_overrides,
        )

        fig = go.Figure(data=traces, layout=layout)
        plotly_json = pio.to_json(fig)

        result: dict[str, str] = {"plotly_json": plotly_json}

        # PNG export — optional, requires kaleido
        try:
            png_bytes = fig.to_image(format="png", width=900, height=500, scale=2)
            result["png_base64"] = "data:image/png;base64," + base64.b64encode(png_bytes).decode()
        except Exception:
            pass  # kaleido not installed — omit png_base64

        return json.dumps(result)

    except (json.JSONDecodeError, TypeError) as exc:
        return f"Data format error: {exc}"
    except Exception as exc:
        logger.warning("Plotly chart creation failed: %s", exc)
        return f"Chart error: {exc}"


# ---------------------------------------------------------------------------
# Public accessor
# ---------------------------------------------------------------------------


def get_writing_tools() -> list:
    """Return the complete list of tools available to the Writing Agent."""
    return [
        generate_report_from_template,
        format_citation,
        extract_markdown_section,
        create_bar_chart,
        create_forest_plot,
        create_plotly_chart,
    ]
